/** AVMA-accredited veterinary schools (representative list for demo UI). */
export const AVMA_ACCREDITED_SCHOOLS = [
  "Auburn University College of Veterinary Medicine",
  "Colorado State University College of Veterinary Medicine and Biomedical Sciences",
  "Cornell University College of Veterinary Medicine",
  "Iowa State University College of Veterinary Medicine",
  "Kansas State University College of Veterinary Medicine",
  "Lincoln Memorial University College of Veterinary Medicine",
  "Louisiana State University School of Veterinary Medicine",
  "Michigan State University College of Veterinary Medicine",
  "Midwestern University College of Veterinary Medicine (AZ)",
  "Midwestern University College of Veterinary Medicine (IL)",
  "Mississippi State University College of Veterinary Medicine",
  "North Carolina State University College of Veterinary Medicine",
  "Ohio State University College of Veterinary Medicine",
  "Oklahoma State University College of Veterinary Medicine",
  "Oregon State University Carlson College of Veterinary Medicine",
  "Purdue University College of Veterinary Medicine",
  "Ross University School of Veterinary Medicine",
  "Royal Veterinary College (affiliate programs)",
  "St. George's University School of Veterinary Medicine",
  "Texas A&M University College of Veterinary Medicine & Biomedical Sciences",
  "Tufts University Cummings School of Veterinary Medicine",
  "University of California, Davis School of Veterinary Medicine",
  "University of Florida College of Veterinary Medicine",
  "University of Georgia College of Veterinary Medicine",
  "University of Illinois College of Veterinary Medicine",
  "University of Minnesota College of Veterinary Medicine",
  "University of Missouri College of Veterinary Medicine",
  "University of Pennsylvania School of Veterinary Medicine",
  "University of Tennessee College of Veterinary Medicine",
  "University of Wisconsin School of Veterinary Medicine",
  "Virginia-Maryland College of Veterinary Medicine",
  "Washington State University College of Veterinary Medicine",
  "Western University of Health Sciences College of Veterinary Medicine",
] as const;
