import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
  RefreshControl,
  Platform,
  Linking,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams, useFocusEffect } from 'expo-router';
import { ArrowLeft, FileText, NotepadText, MapPin, Plus, TestTubeDiagonal, Syringe, Stethoscope } from 'lucide-react-native';
import { clerkApiClient } from '../../../../lib/api';
import { Document } from '../../../../store/documents';

// Category configuration
const CATEGORY_CONFIG = {
  'veterinary_notes': {
    title: 'Veterinary Notes',
    icon: NotepadText,
  },
  'diagnostic_reports_and_imaging': {
    title: 'Diagnostic Reports',
    icon: Stethoscope,
  },
  'lab_results': {
    title: 'Lab Results',
    icon: TestTubeDiagonal,
  },
  'vaccine_record': {
    title: 'Vaccine Records',
    icon: Syringe,
  },
} as const;

// Standard blue color for all categories
const PRIMARY_COLOR = '#4559A7';
const LIGHT_BLUE = '#ADD7EB';

// Helper functions
const formatDate = (dateString: string) => {
  return new Date(dateString).toLocaleDateString();
};

// Document Card Component
interface DocumentCardProps {
  document: Document;
  category: string;
  onView: (document: Document) => void;
}

function DocumentCard({ document, category, onView }: DocumentCardProps) {
  const IconComponent = CATEGORY_CONFIG[category as keyof typeof CATEGORY_CONFIG]?.icon || FileText;
  const rawName = (document as any).fileName || '';
  const isAutoGenerated = typeof rawName === 'string' && rawName.startsWith('doc-');
  const displayName = (!isAutoGenerated && rawName?.trim())
    ? rawName
    : ((document as any).originalFileName || rawName);
  
  return (
    <TouchableOpacity 
      style={styles.documentCard}
      onPress={() => onView(document)}
      activeOpacity={0.7}
    >
      <View style={styles.documentHeader}>
        <View style={styles.documentIcon}>
          <IconComponent size={24} color="#FFFFFF" />
        </View>
        <View style={styles.documentInfo}>
          <Text style={styles.documentName}>{displayName}</Text>
          <Text style={styles.documentDate}>
            {formatDate(document.date || document.createdAt)}
          </Text>
          {document.hospitalName && (
            <View style={styles.hospitalInfo}>
              <MapPin size={14} color={PRIMARY_COLOR} />
              <Text style={styles.hospitalName}>{document.hospitalName}</Text>
            </View>
          )}
        </View>
      </View>
      
      {document.notes && (
        <Text style={styles.documentNotes}>{document.notes}</Text>
      )}
    </TouchableOpacity>
  );
}

// Main Component
export default function CategoryDocumentsScreen() {
  // Route is /pets/[id]/docs/[category]
  const { category, id } = useLocalSearchParams();
  const petId = id as string | undefined;
  const [documents, setDocuments] = useState<Document[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const categoryTitle = CATEGORY_CONFIG[category as keyof typeof CATEGORY_CONFIG]?.title || 'Documents';

  const fetchDocuments = React.useCallback(async () => {
    if (!category) return;
    
    setLoading(true);
    try {
      console.log(`🔍 Fetching documents for category: ${category}, pet: ${petId}`);
      
      const response = petId 
        ? await clerkApiClient.getDocumentsByPetAndCategory(petId as string, category as string)
        : await clerkApiClient.getDocumentsByCategory(category as string);
      
      if (response.success) {
        console.log('📄 Documents count:', response.data?.length || 0);
        setDocuments(response.data || []);
      }
    } catch (error) {
      console.error('Error fetching documents:', error);
      Alert.alert('Error', 'Failed to load documents');
    } finally {
      setLoading(false);
    }
  }, [category, petId]);

  useEffect(() => {
    fetchDocuments();
  }, [fetchDocuments]);

  useFocusEffect(
    React.useCallback(() => {
      console.log('🔄 Screen focused, refreshing documents...');
      fetchDocuments();
    }, [fetchDocuments])
  );

  const onRefresh = async () => {
    setRefreshing(true);
    await fetchDocuments();
    setRefreshing(false);
  };

  const handleViewDocument = async (document: Document) => {
    try {
      const json = await clerkApiClient.getDocumentPresignedUrl(document.id);
      if (json.success && json.data?.url) {
        // Open the document directly in the browser/external viewer
        if (Platform.OS === 'web') {
          window.open(json.data.url, '_blank');
        } else {
          await Linking.openURL(json.data.url);
        }
      } else {
        Alert.alert('Error', 'Unable to get a secure download link. Please try again.');
      }
    } catch (error) {
      console.error('Error opening document:', error);
      Alert.alert('Error', 'Failed to open document. Please try again.');
    }
  };

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView 
        style={styles.scrollView}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={onRefresh}
            colors={[PRIMARY_COLOR]}
            tintColor={PRIMARY_COLOR}
          />
        }
      >
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity 
            onPress={() => router.push(`/(tabs)/pets/${petId}/docs` as any)} 
            style={styles.backButton}
          >
            <ArrowLeft size={24} color={PRIMARY_COLOR} />
          </TouchableOpacity>
          <Text style={styles.title}>{categoryTitle}</Text>
          <View style={styles.placeholder} />
        </View>

        {/* Documents List */}
        {loading ? (
          <View style={styles.loadingContainer}>
            <Text style={styles.loadingText}>Loading documents...</Text>
          </View>
        ) : documents.length === 0 ? (
          <View style={styles.emptyContainer}>
            <FileText size={64} color={LIGHT_BLUE} />
            <Text style={styles.emptyTitle}>No Documents Yet</Text>
            <TouchableOpacity
              style={styles.addFirstDocButton}
              onPress={() => router.push({
                pathname: `/(tabs)/pets/${petId}/docs/upload` as any,
                params: { category: category }
              })}
            >
              <Plus size={20} color="#FFFFFF" />
              <Text style={styles.addFirstDocButtonText}>Add First Document</Text>
            </TouchableOpacity>
          </View>
        ) : (
          <View style={styles.documentsContainer}>
            {documents.map((document) => (
              <DocumentCard
                key={document.id}
                document={document}
                category={category as string}
                onView={handleViewDocument}
              />
            ))}
          </View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollView: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: LIGHT_BLUE,
  },
  backButton: {
    padding: 8,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
  },
  placeholder: {
    width: 40,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  loadingText: {
    fontSize: 16,
    color: PRIMARY_COLOR,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: PRIMARY_COLOR,
    marginTop: 16,
    marginBottom: 24,
  },
  addFirstDocButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: PRIMARY_COLOR,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 8,
  },
  addFirstDocButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  emptyDescription: {
    fontSize: 14,
    color: PRIMARY_COLOR,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },
  addButton: {
    backgroundColor: PRIMARY_COLOR,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  documentsContainer: {
    padding: 20,
  },
  documentCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: LIGHT_BLUE,
  },
  documentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  documentIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: PRIMARY_COLOR,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  documentInfo: {
    flex: 1,
  },
  documentName: {
    fontSize: 18,
    fontWeight: '600',
    color: PRIMARY_COLOR,
    marginBottom: 4,
  },
  documentDate: {
    fontSize: 16,
    color: PRIMARY_COLOR,
    marginBottom: 4,
  },
  hospitalInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  hospitalName: {
    fontSize: 12,
    color: PRIMARY_COLOR,
    marginLeft: 4,
  },
  documentNotes: {
    fontSize: 14,
    color: PRIMARY_COLOR,
    fontStyle: 'italic',
    marginBottom: 12,
    paddingLeft: 60,
  },
  fab: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: PRIMARY_COLOR,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  // Modal styles
  modalContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: LIGHT_BLUE,
  },
  closeButton: {
    padding: 8,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
  },
  modalContent: {
    flex: 1,
    padding: 20,
  },
  documentViewer: {
    alignItems: 'center',
  },
  viewerIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: PRIMARY_COLOR,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  documentDetails: {
    width: '100%',
    alignItems: 'center',
  },
  documentTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
    textAlign: 'center',
    marginBottom: 8,
  },
  documentCategory: {
    fontSize: 16,
    color: PRIMARY_COLOR,
    opacity: 0.7,
    marginBottom: 24,
  },
  metadataContainer: {
    width: '100%',
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  metadataRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  metadataLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: PRIMARY_COLOR,
    marginLeft: 8,
    marginRight: 8,
    minWidth: 60,
  },
  metadataValue: {
    fontSize: 14,
    color: PRIMARY_COLOR,
    flex: 1,
  },
  notesContainer: {
    width: '100%',
    backgroundColor: '#F0F8FF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: PRIMARY_COLOR,
  },
  notesLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: PRIMARY_COLOR,
    marginBottom: 8,
  },
  notesText: {
    fontSize: 14,
    color: PRIMARY_COLOR,
    lineHeight: 20,
  },
  technicalDetails: {
    width: '100%',
    backgroundColor: '#F0F8FF',
    borderRadius: 12,
    padding: 16,
    borderLeftWidth: 4,
    borderLeftColor: LIGHT_BLUE,
  },
  technicalLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: PRIMARY_COLOR,
    marginBottom: 12,
  },
  technicalText: {
    fontSize: 12,
    color: PRIMARY_COLOR,
    opacity: 0.8,
    marginBottom: 4,
    fontFamily: 'monospace',
  },
  modalActions: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: LIGHT_BLUE,
    alignItems: 'center',
  },
  viewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PRIMARY_COLOR,
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: 16,
    gap: 12,
    minWidth: 200,
  },
  viewButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  imagePreviewContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    paddingHorizontal: 20,
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  imagePreviewIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: PRIMARY_COLOR,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  imagePreviewText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 4,
  },
  imagePreviewSubtext: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
  },
});
